baseURL = "https://nayr.net/"
languageCode = "en-us"
title = "|nayr|NETworks|"
theme = "hugo-theme-air"
paginate = 5
DisqusShortname = ""
canonifyurls = true
sectionPagesMenu = "main"
EnableGitInfo = "true"

[author]
  name = "admin"
  bio = "Network Admin"
  location = "Denver, CO"
  website = "http://nayr.com"
[params]
  description = "networks for nothing"
  cover = "images/avatar.png"
  author = "admin"
  authorlocation = "Denver, CO"
  authorwebsite = "https://nayr.com"
  bio= "network admin of nayr.net"
  logo = "images/avatar.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "nayrnet"
  twitterName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  mainSections = ["post"]
